dataset_type: "roc_stories_no_title"
path_to_cashed_data: "./data/token/cashed_for_gpt2_anon"
is_uncased: True
pretrained_tokenizer: "data/tokenizer/official_gpt2_encoder"
max_sent_len: 75
padding_len: 100
overlap: 40
batch_size: 32
model_version: 1
log_dir: "./gpt2-small"