pretrained_name: "gpt2"
lr: 0.0001
epochs: 50
train_context: 0.
target_types_pred: 0.5
real_types_match: 0.25
adaptation_part: 0.25
div_factor: 10000
log_dir: "./gpt2-small"
model_version: 10
ner_model_version: 3