path_to_cashed_data: "./data/token/cashed_for_gpt2_anon"
is_uncased: True
pretrained_tokenizer: "data/tokenizer/official_gpt2_encoder"
max_full_ex_len: 128
max_only_context_len: 96
overlap: 40
batch_size: 32
model_version: 12
log_dir: "./gpt2-small"