train_data_path: "./data/token/train"
train_data_type: "2006"
validate_data_path: "./data/token/test"
val_data_type: "2006"
other_label: "O"
is_uncased: False
pretrained_tokenizer_path: "bert-base-cased"
max_token_number: 100
eq_max_padding: False
batch_size: 32
