train_data_path: "./data/token/train"
train_xml_type: "2006"
validate_data_path: "./data/token/test"
val_xml_type: "2006"
other_label: "O"
is_uncased: False
pretrained_tokenizer_path: "bert-base-cased"
max_token_number: 100
batch_size: 32
