dataset_type: "i2b2fourteen"
train_data_path: "./data/token/i2b2-2014/train"
validate_data_path: "./data/token/i2b2-2014/test"
other_label: "O"
is_uncased: True
pretrained_tokenizer: "bert-large-uncased" # "bert-base-cased" / "bert-base-uncased" / "bert-large-cased" / "bert-large-uncased"
max_token_number: 100
overlap: 40
eq_max_padding: True
batch_size: 32