type: "ref_book"
path_to_first_male_names: "./data/anon_books/first_names_female.txt"
path_to_first_femail_names: "./data/anon_books/first_names_male.txt"
path_to_last_names: "./data/anon_books/last_names.txt"
path_to_full_addresses: "./data/anon_books/addresses.txt"
path_to_countries: "./data/anon_books/countries.txt"
path_to_states: "./data/anon_books/states.txt"
path_to_cities: "./data/anon_books/cities.txt"
path_to_streets: "./data/anon_books/streets.txt"
path_to_organizations: "./data/anon_books/organisations.txt"
path_to_hospitals: "./data/anon_books/sampled_hospitals.txt"
path_to_professions: "./data/anon_books/professions.txt"