dataset_type: "roc_stories_no_title"
train_data_path: "data/token/roc_stories_train.pkl"
valid_data_path: "data/token/roc_stories_valid.pkl"
is_uncased: True
mask_p: 0.1
max_span_len: 8
max_num_train_examples: 4096 # 15000
max_num_valid_examples: 2048 # 3000
num_examples_per_doc: 1
max_num_retries_per_ex: 3
min_masked_spans_per_ex: 1
max_masked_spans_per_ex: 5
pretrained_tokenizer: "data/tokenizer/official_gpt2_encoder"
max_token_number: 64
overlap: 16

batch_size: 16